Traceback (most recent call last):
  File "/home/ivan/src/evolutiz/util/multiple_queue_consumer_thread.py", line 68, in run
    result = self.func(*args, **self.extra_kwargs)
  File "/home/ivan/src/evolutiz/algorithms/standard.py", line 82, in generate_two_offspring
    assert len(o1) > 1
AssertionError

Traceback (most recent call last):
  File "main.py", line 55, in run_one_app
    test_generator.run()
  File "/home/ivan/src/evolutiz/evolutiz.py", line 45, in run
    population = self.strategy.run()
  File "/home/ivan/src/evolutiz/algorithms/genetic_algorithm.py", line 27, in run
    success = self.initPopulation()
  File "/home/ivan/src/evolutiz/algorithms/genetic_algorithm.py", line 41, in initPopulation
    invalid_ind = [ind for ind in self.population if not ind.fitness.valid]
  File "/home/ivan/src/evolutiz/algorithms/genetic_algorithm.py", line 41, in <listcomp>
    invalid_ind = [ind for ind in self.population if not ind.fitness.valid]
AttributeError: 'NoneType' object has no attribute 'fitness'


Se cuelga en:
Running command: $ANDROID_HOME/platform-tools/adb -s emulator-5572 shell pm list package

(corriendo al mismo tiempo "adb -s emulator-5572 shell" también se cuelga)
=> No está funcionando el timeout de 30s de subprocess.run

Ahora parece que está funcionando el timeout:

Traceback (most recent call last):
  File "main.py", line 48, in run_one_app
    prepare_devices(result_dir)
  File "main.py", line 78, in prepare_devices
    device.clean_sdcard()
  File "/home/ivan/src/evolutiz/devices/emulator.py", line 69, in clean_sdcard
    adb.get_root_permissions(self)
  File "/home/ivan/src/evolutiz/devices/adb.py", line 48, in get_root_permissions
    raise Exception("Unable to gain root permissions on device: " + device.name)
Exception: Unable to gain root permissions on device: emulator-5572

